### ISSUE TITLE
How to run it 

### ISSUE THREAD

**Issue by nishant-aka-nik** [atuuuu/Anime_Downloader#1]
Hi can you please update in readme on how run this script I need this downloader to integrate it with my small project, but I am unable to run it can you please help

**Comment by atuuuu** [comment]
hello, sure I'm working on it
this project is my first in Go so it's a real mess, I'll also do some cleaning

**Comment by atuuuu** [comment]
Hello again,
I improved the imports and I added a makefile
You just have to run "make build" and it should generate an executable
If you're on windows, you can also run "make run" and it should run fine
Let me know if something's still wrong
